
- name: Provision Web Servers
  hosts: tag_group_web
  become: true
  tasks:
    - name: Install python pip3
      apt:
        update_cache: yes
        name:
          - python3-pip
    
    - name: install docker and docker-compose
      pip:
        name:
          - docker
          - docker-compose

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: copy staycation folder to /opt
      copy:
        src: ../../staycationX
        dest: /opt
   

    - name: Run docker-compose
      shell: docker-compose -f /opt/staycationX/docker-compose.yml up -d --build
   