
- name: Provision Web Servers
  hosts: tag_group_web
  become: true
  tasks:
    - name: Install pip3, docker and docker compose
      apt:
        update_cache: yes
        name:
          - python3-pip
    
    - name: install docker and docker-compose
      shell: apt update && apt install -y docker.io docker-compose

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: print current directory
      shell: pwd && ls -la

    - name: copy staycation folder to /opt
      copy:
        src: ../../staycationX
        dest: /opt
   

    - name: Run docker-compose
      shell: docker-compose -f /opt/staycationX/docker-compose.yml up -d
   